// import './basic_type'
// import './symbol.ts'
// import './interface'
// import './function'
// import './generics'
import './class.ts'
// import './advanced'
// import './advanced2'
// import './decorators'
